version: '2'
services:
  android-mkdocs:
    image: squidfunk/mkdocs-material:4.6.0
    container_name: android-mkdocs
    ports:
      - "8001:8001"
    volumes:
      - ./:/docs
    tty: true
    environment:
      - GITHUB_ACTIONS=$GITHUB_ACTIONS
    entrypoint: /bin/sh /docs/entrypoint.sh